apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbhydra-pvc
  namespace: media-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 4Gi
