apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbhydra-longhorn-pvc
  namespace: media-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
