apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-longhorn-pvc
  namespace: media-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
