apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apprise-longhorn-pvc
  namespace: general-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
