apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: media-services
spec:
  selector:
    app: flaresolverr
  ports:
    - name: flaresolverr
      port: 8191
      targetPort: 8191
